# Generated by Django 5.0.1 on 2024-08-20 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('material', '0001_initial'),
        ('unidade', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CautelaMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(blank=True, max_length=15, null=True)),
                ('especie', models.CharField(blank=True, max_length=30, null=True)),
                ('modelo', models.CharField(blank=True, max_length=30, null=True)),
                ('fabricante', models.CharField(blank=True, max_length=30, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('data_cautela', models.DateField(auto_now_add=True)),
                ('responsavel', models.CharField(max_length=255)),
                ('matricula', models.CharField(max_length=50)),
                ('sgpe', models.CharField(max_length=50)),
                ('quantidade', models.IntegerField(blank=True, null=True, verbose_name='Quantidade')),
                ('material_geral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.material')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unidade.unidade')),
            ],
        ),
    ]
