# Generated by Django 5.0.1 on 2024-08-20 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomefantasia', models.CharField(max_length=80, verbose_name='NOME FANTASIA')),
                ('razaosocial', models.CharField(max_length=80, verbose_name='RAZÃO SOCIAL')),
                ('endereco', models.CharField(max_length=100, verbose_name='ENDEREÇO')),
                ('telefone', models.CharField(max_length=50, verbose_name='TELEFONE')),
                ('email', models.CharField(max_length=80, verbose_name='email')),
            ],
        ),
    ]
