# Generated by Django 5.0.1 on 2024-08-20 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('unidade', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restricoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(max_length=40, verbose_name='Nº SÉRIE')),
                ('patrimonio', models.CharField(max_length=40, verbose_name='Nº PATRIMÔNIO')),
                ('sinarm', models.CharField(blank=True, max_length=40, null=True, verbose_name='Nº SINARM')),
                ('especie', models.CharField(max_length=40, verbose_name='ESPÉCIE')),
                ('marca', models.CharField(max_length=40, verbose_name='MARCA')),
                ('modelo', models.CharField(max_length=40, verbose_name='MODELO')),
                ('calibre', models.CharField(blank=True, max_length=40, null=True, verbose_name='CALIBRE')),
                ('servidor', models.CharField(max_length=40, verbose_name='SERVIDOR')),
                ('telefone', models.CharField(blank=True, max_length=40, null=True, verbose_name='TELEFONE')),
                ('cargo', models.CharField(blank=True, max_length=40, null=True, verbose_name='CARGO')),
                ('matricula', models.CharField(max_length=40, verbose_name='MATRÍCULA')),
                ('sgperecebimento', models.CharField(max_length=40, verbose_name='SGPE COMUNICAÇÃO')),
                ('situacao', models.CharField(blank=True, max_length=40, null=True, verbose_name='SITUAÇÃO')),
                ('tipo', models.CharField(blank=True, max_length=40, null=True, verbose_name='TIPO')),
                ('datacautela', models.DateField(blank=True, null=True, verbose_name='DATA DA CAUTELA')),
                ('atualizacao', models.CharField(blank=True, max_length=40, null=True, verbose_name='ATUALIZAÇÃO')),
                ('historico', models.TextField(blank=True, null=True, verbose_name='HISTÓRICO')),
                ('local', models.CharField(blank=True, max_length=40, null=True, verbose_name='SITUAÇÃO')),
                ('motivo', models.CharField(max_length=40, verbose_name='MOTIVO')),
                ('prazo', models.CharField(blank=True, max_length=40, null=True, verbose_name='PRAZO')),
                ('responsavelcadastramento', models.CharField(max_length=40, verbose_name='RESPONSÁVEL CADASTRO')),
                ('datacadastramento', models.DateField(blank=True, null=True, verbose_name='DATA CADASTRO')),
                ('responsavelrecebimento', models.CharField(blank=True, max_length=40, null=True, verbose_name='REPONSÁVEL RECEBIMENTO')),
                ('datarecebimento', models.DateField(blank=True, null=True, verbose_name='DATA RECEBIMENTO')),
                ('responsavelentrega', models.CharField(blank=True, max_length=120, null=True, verbose_name='RESPONSÁVEL ENTREGA')),
                ('responsaveldevolucao', models.CharField(blank=True, max_length=40, null=True, verbose_name='RESPONSÁVEL DEVOLUÇÃO')),
                ('datadevolucao', models.DateField(blank=True, null=True, verbose_name='DATA DEVOLUÇÃO')),
                ('obsevacoes', models.CharField(blank=True, max_length=40, null=True, verbose_name='OBSERVAÇÕES')),
                ('sgpedevolucao', models.CharField(blank=True, max_length=40, null=True, verbose_name='SGPE DEVOLUÇÃO')),
                ('lotacao', models.ForeignKey(db_column='lotacao', on_delete=django.db.models.deletion.PROTECT, related_name='LOTAÇÃO', to='unidade.unidade')),
            ],
        ),
    ]
