# Generated by Django 5.0.1 on 2024-08-20 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('unidade', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Municao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gens', models.CharField(max_length=30, verbose_name='GENS')),
                ('calibre', models.CharField(blank=True, max_length=30, null=True, verbose_name='CALIBRE')),
                ('tipo', models.CharField(blank=True, max_length=30, null=True, verbose_name='TIPO')),
                ('marca', models.CharField(blank=True, max_length=30, null=True, verbose_name='MARCA')),
                ('quantidade', models.CharField(max_length=30, verbose_name='QUANTIDADE')),
                ('nome', models.CharField(max_length=30, verbose_name='NOME')),
                ('matricula', models.CharField(blank=True, max_length=20, null=True, verbose_name='MATRICULA')),
                ('data', models.DateField(blank=True, null=True, verbose_name='DATA')),
                ('sgpe', models.CharField(max_length=30, verbose_name='SGPE')),
                ('responsavel', models.CharField(max_length=30, verbose_name='RESPONSÁVEL')),
                ('observacoes', models.CharField(blank=True, max_length=1200, null=True, verbose_name='OBSERVAÇÕES')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='unidade.unidade')),
            ],
        ),
    ]
