# Generated by Django 5.0.1 on 2024-08-20 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('unidade', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oficina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataentrada', models.DateField(blank=True, null=True, verbose_name='DATA DE ENTRADA')),
                ('datasaida', models.DateField(blank=True, null=True, verbose_name='DATA DE SAÍDA')),
                ('numeroseria', models.CharField(max_length=50, verbose_name='NUMERO DE SÉRIE')),
                ('especie', models.CharField(max_length=100, verbose_name='ESPÉCIE')),
                ('modelo', models.CharField(max_length=100, verbose_name='MODELO')),
                ('cargapara', models.CharField(max_length=100, verbose_name='CARGA PARA')),
                ('historico', models.CharField(max_length=500, verbose_name='HISTÓRICO')),
                ('servico', models.CharField(blank=True, max_length=500, null=True, verbose_name='SERVIÇO')),
                ('usuario', models.CharField(blank=True, max_length=30, null=True, verbose_name='USUÁRIO')),
                ('armeiro', models.CharField(blank=True, max_length=100, null=True, verbose_name='ARMEIRO')),
                ('dataconcerto', models.DateField(blank=True, null=True, verbose_name='DATA DE CONCERTO')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='unidade.unidade')),
            ],
        ),
    ]
