# Generated by Django 5.0.1 on 2024-08-20 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('user', models.CharField(blank=True, max_length=15, null=True, verbose_name='USER')),
                ('unidade', models.CharField(blank=True, max_length=200, null=True, verbose_name='UNIDADE')),
                ('matricula', models.CharField(blank=True, max_length=15, null=True, verbose_name='MATRICULA')),
                ('cpf', models.CharField(blank=True, max_length=15, null=True, verbose_name='CPF')),
                ('endereco', models.CharField(blank=True, max_length=200, null=True, verbose_name='ENDEREÇO')),
                ('telefone', models.CharField(blank=True, max_length=50, null=True, verbose_name='TELEFONE')),
                ('email', models.CharField(blank=True, max_length=120, null=True, verbose_name='EMAIL')),
                ('funcao', models.CharField(blank=True, max_length=100, null=True, verbose_name='FUNÇÃO')),
                ('cidade', models.CharField(blank=True, max_length=200, null=True, verbose_name='CIDADE')),
            ],
        ),
    ]
