# Generated by Django 5.0.1 on 2024-08-20 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iis', models.CharField(blank=True, max_length=10, null=True, verbose_name='NUMERO DE SÉRIE')),
                ('serie', models.CharField(blank=True, max_length=15, null=True, verbose_name='CNPJ')),
                ('especie', models.CharField(blank=True, max_length=30, null=True, verbose_name='Nº PATRIMÔNIO')),
                ('modelo', models.CharField(blank=True, max_length=30, null=True, verbose_name='Nº SINARM')),
                ('fabricante', models.CharField(blank=True, max_length=30, null=True, verbose_name='ESPÉCIE')),
                ('material', models.CharField(blank=True, max_length=30, null=True, verbose_name='ESPÉCIE')),
                ('cor', models.CharField(blank=True, max_length=15, null=True, verbose_name='MODELO')),
                ('altura', models.CharField(blank=True, max_length=10, null=True, verbose_name='CALIBRE')),
                ('largura', models.CharField(blank=True, max_length=10, null=True, verbose_name='CAPACIDADE')),
                ('pesoliquido', models.CharField(blank=True, max_length=10, null=True, verbose_name='QUANTIDADE DE CARREGADORES')),
                ('pesobruto', models.CharField(blank=True, max_length=10, null=True, verbose_name='FUNCIONAMENTO')),
                ('retardo', models.CharField(blank=True, max_length=15, null=True, verbose_name='ACABAMENTO')),
                ('duploestagio', models.CharField(blank=True, max_length=15, null=True, verbose_name='QUANTIDADE DE CANOS')),
                ('unidade', models.CharField(blank=True, max_length=150, null=True, verbose_name='UNIDADE')),
                ('situacao', models.CharField(blank=True, max_length=30, null=True, verbose_name='SITUAÇÃO')),
                ('sgpecautela', models.CharField(blank=True, max_length=30, null=True, verbose_name='SGPE CAUTELA')),
                ('datacautela', models.DateField(blank=True, null=True, verbose_name='DATA DA CAUTELA')),
                ('sgpetroca', models.CharField(blank=True, max_length=30, null=True, verbose_name='SGPE TROCA')),
                ('datatroca', models.DateField(blank=True, null=True, verbose_name='DATA DA TROCA')),
                ('quantidade', models.IntegerField(blank=True, null=True, verbose_name='QUANTIDADE')),
            ],
        ),
        migrations.CreateModel(
            name='Municao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gens', models.CharField(max_length=30, verbose_name='GENS')),
                ('calibre', models.CharField(max_length=30, verbose_name='CALIBRE')),
                ('modelo', models.CharField(max_length=30, verbose_name='MODELO')),
                ('fabricante', models.CharField(max_length=30, verbose_name='ESPÉCIE')),
                ('qtdcaixas', models.IntegerField(verbose_name='QTD CAIXAS')),
                ('qtdproduto', models.IntegerField(verbose_name='QTD PRODUTO')),
            ],
        ),
        migrations.CreateModel(
            name='Projetil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gens', models.CharField(max_length=30, verbose_name='GENS')),
                ('calibre', models.CharField(max_length=30, verbose_name='CALIBRE')),
                ('modelo', models.CharField(max_length=30, verbose_name='MODELO')),
                ('fabricante', models.CharField(max_length=30, verbose_name='ESPÉCIE')),
                ('qtdcaixas', models.IntegerField(verbose_name='QTD CAIXAS')),
                ('qtdproduto', models.IntegerField(verbose_name='QTD PRODUTO')),
            ],
        ),
    ]
