# Generated by Django 5.0.1 on 2024-08-20 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroserie', models.CharField(max_length=40, verbose_name='NUMERO DE SÉRIE')),
                ('cnpj', models.CharField(max_length=30, verbose_name='CNPJ')),
                ('numeropatri', models.CharField(max_length=30, verbose_name='Nº PATRIMÔNIO')),
                ('especie', models.CharField(max_length=50, verbose_name='ESPÉCIE')),
                ('pais', models.CharField(max_length=30, verbose_name='PAÍS')),
                ('marca', models.CharField(max_length=50, verbose_name='MARCA')),
                ('nivel', models.CharField(max_length=50, verbose_name='NÍVEL')),
                ('sexo', models.CharField(max_length=50, verbose_name='SEXO')),
                ('tamanho', models.CharField(max_length=50, verbose_name='TAMANHO')),
                ('modelo', models.CharField(blank=True, max_length=50, null=True, verbose_name='MODELO')),
                ('lote', models.CharField(blank=True, max_length=25, null=True, verbose_name='LOTE')),
                ('datafabricacao', models.DateField(blank=True, null=True, verbose_name='DATA DA FABRICAÇÃO')),
                ('garantia', models.CharField(blank=True, max_length=20, null=True, verbose_name='GARANTIA')),
                ('capa', models.CharField(blank=True, max_length=200, null=True, verbose_name='CAPA')),
                ('servidor', models.CharField(blank=True, max_length=150, null=True, verbose_name='SERVIDOR')),
                ('cargo', models.CharField(blank=True, max_length=50, null=True, verbose_name='CARGO')),
                ('unidade', models.CharField(blank=True, max_length=150, null=True, verbose_name='UNIDADE')),
                ('sgpe', models.CharField(blank=True, max_length=50, null=True, verbose_name='SGPE')),
                ('situacao', models.CharField(blank=True, max_length=100, null=True, verbose_name='SITUAÇÃO')),
                ('datacautela', models.DateField(blank=True, null=True, verbose_name='DATA DA CAUTELA')),
                ('atualizacao', models.CharField(blank=True, max_length=50, null=True, verbose_name='ATUALIZAÇÃO')),
                ('historico', models.CharField(blank=True, max_length=600, null=True, verbose_name='HISTÓRICO')),
                ('matricula', models.CharField(blank=True, max_length=300, null=True, verbose_name='MATRICULA')),
                ('tipo', models.CharField(blank=True, max_length=300, null=True, verbose_name='TIPO')),
                ('datadevolucao', models.DateField(blank=True, null=True, verbose_name='DATA DA DEVOLUÇÃO')),
                ('observacoes', models.CharField(blank=True, max_length=1000, null=True, verbose_name='OBSERVAÇÕES')),
            ],
        ),
    ]
