# Generated by Django 5.0.1 on 2024-08-20 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Arma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroserie', models.CharField(max_length=30, verbose_name='NUMERO DE SÉRIE')),
                ('cnpj', models.CharField(blank=True, max_length=20, null=True, verbose_name='CNPJ')),
                ('numeropatri', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nº PATRIMÔNIO')),
                ('numerosinarm', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nº SINARM')),
                ('especie', models.CharField(max_length=30, verbose_name='ESPÉCIE')),
                ('marca', models.CharField(max_length=30, verbose_name='MARCA')),
                ('modelo', models.CharField(max_length=30, verbose_name='MODELO')),
                ('calibre', models.CharField(max_length=30, verbose_name='CALIBRE')),
                ('capacidade', models.CharField(max_length=30, verbose_name='CAPACIDADE')),
                ('qtcarregador', models.CharField(max_length=30, verbose_name='QUANTIDADE DE CARREGADORES')),
                ('funcionamento', models.CharField(max_length=20, verbose_name='FUNCIONAMENTO')),
                ('acabamento', models.CharField(max_length=15, verbose_name='ACABAMENTO')),
                ('qtcanos', models.CharField(max_length=10, verbose_name='QUANTIDADE DE CANOS')),
                ('compricanos', models.CharField(max_length=15, verbose_name='COMPRIMENTO DE CANOS')),
                ('tipoalma', models.CharField(max_length=10, verbose_name='TIPO DE ALMA')),
                ('qtraias', models.CharField(max_length=10, verbose_name='QUANTIDADE DE RAIAS')),
                ('sentidorais', models.CharField(max_length=10, verbose_name='SENTIDO DAS RAIAS')),
                ('paisfabricacao', models.CharField(max_length=30, verbose_name='PAIS DE FABRICAÇÃO')),
                ('acessorios', models.CharField(max_length=100, verbose_name='ACESSORIOS')),
                ('docregistro', models.CharField(blank=True, max_length=150, null=True, verbose_name='DOCUMENTO DE REGISTRO')),
                ('tipomunicao', models.CharField(max_length=30, verbose_name='TIPO DE MUNIÇÃO')),
                ('datacompra', models.DateField(blank=True, null=True, verbose_name='DATA DA COMPRA')),
                ('unidade', models.CharField(blank=True, max_length=150, null=True, verbose_name='UNIDADE')),
                ('servidor', models.CharField(blank=True, max_length=150, null=True, verbose_name='SERVIDOR')),
                ('gensmunicao', models.CharField(blank=True, max_length=50, null=True, verbose_name='GENS DA MUNIÇÃO')),
                ('qtmunicao', models.CharField(blank=True, max_length=10, null=True, verbose_name='QUANTIDADE DE MUNIÇÃO')),
                ('observacoes', models.CharField(blank=True, max_length=150, null=True, verbose_name='OBSERVAÇÕES')),
                ('matricula', models.CharField(blank=True, max_length=150, null=True, verbose_name='MATRICULA')),
                ('telefone', models.CharField(blank=True, max_length=80, null=True, verbose_name='TELEFONE')),
                ('datacautela', models.DateField(blank=True, null=True, verbose_name='DATA DA CAUTELA')),
                ('numerosgpe', models.CharField(blank=True, max_length=30, null=True, verbose_name='NUMERO SGPE')),
                ('responsavel', models.CharField(blank=True, max_length=140, null=True, verbose_name='RESPONSAVEL')),
                ('tipo', models.CharField(blank=True, max_length=30, null=True, verbose_name='TIPO')),
                ('situacao', models.CharField(blank=True, max_length=40, null=True, verbose_name='SITUAÇÂO')),
                ('regional', models.CharField(blank=True, max_length=80, null=True, verbose_name='REGIONAL')),
                ('datadevolucao', models.DateField(blank=True, null=True, verbose_name='DATA DA DEVOLUÇÃO')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
