# Generated by Django 5.0.1 on 2024-08-20 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArmaParticular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroserie', models.CharField(max_length=30, verbose_name='NUMERO DE SÉRIE')),
                ('nome', models.CharField(max_length=30, verbose_name='NOME')),
                ('cpf', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nº CPF')),
                ('rg', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nº RG')),
                ('numerosigma', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nº SIGMA')),
                ('numerosinarm', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nº SINARM')),
                ('numeroregistro', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nº REGISTRO')),
                ('amparo', models.CharField(max_length=30, verbose_name='AMPARO LEGAL')),
                ('tipo', models.CharField(max_length=30, verbose_name='TIPO')),
                ('marca', models.CharField(max_length=30, verbose_name='MARCA')),
                ('calibre', models.CharField(max_length=30, verbose_name='CALIBRE')),
                ('dataexpedicao', models.DateField(blank=True, null=True, verbose_name='DATA DE EXPEDIÇÃO')),
                ('datavalidade', models.DateField(blank=True, null=True, verbose_name='DATA DE VALIDADE')),
                ('documento', models.FileField(blank=True, null=True, upload_to='pdfs_arma_particular/', verbose_name='PDF')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='pdfs_arma_particular/')),
                ('imagem2', models.ImageField(blank=True, null=True, upload_to='pdfs_arma_particular/')),
                ('imagem3', models.ImageField(blank=True, null=True, upload_to='pdfs_arma_particular/')),
            ],
        ),
    ]
