# Generated by Django 5.0.1 on 2024-08-20 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, verbose_name='NOME')),
                ('telefone', models.CharField(max_length=30, verbose_name='TELEFONE')),
                ('email', models.CharField(max_length=50, verbose_name='E-MAIL')),
                ('endereco', models.CharField(max_length=150, verbose_name='ENDEREÇO')),
                ('gestor', models.CharField(max_length=40, verbose_name='GESTOR')),
                ('orgao', models.CharField(max_length=40, verbose_name='ÓRGÃO')),
            ],
        ),
    ]
